//DATA
const SET_DATA                  = "SET_DATA";
const DATA_FILLED_SUCCESS       = "DATA_FILLED_SUCCESS";
const DATA_FILLED_ERROR         = "DATA_FILLED_ERROR";

//SELECTDATA
const SET_DEFAULT_SELECTED_DATA = "SET_DEFAULT_SELECTED_DATA";
const SET_FACT_SELECTED         = "SET_FACT_SELECTED";
const SET_MARKET_SELECTED       = "SET_MARKET_SELECTED";
const SET_CATEGORY_SELECTED     = "SET_CATEGORY_SELECTED";
const SET_LAST_PERIOD           = "SET_LAST_PERIOD_SELECTED";
const SELECTED_DATA_SUCCESS     = "SELECTED_DATA_SUCCESS";
const SELECTED_DATA_ERROR       = "SELECTED_DATA_ERROR";
